-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Create Enums
create type public.grade_level as enum (
  'creche', 'nursery', 'kg1', 'kg2', 
  'primary1', 'primary2', 'primary3', 'primary4', 'primary5', 'primary6', 
  'jhs1', 'jhs2', 'jhs3'
);

create type public.application_status as enum (
  'pending', 'under_review', 'approved', 'rejected', 'waitlisted', 'withdrawn'
);

create type public.user_role as enum (
  'parent', 'admin', 'staff', 'student'
);

create type public.gender as enum (
  'male', 'female', 'other', 'prefer_not_to_say'
);

-- Profiles Table
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text not null,
  full_name text,
  phone text,
  role public.user_role default 'parent',
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Applications Table
create table public.applications (
  id uuid default uuid_generate_v4() primary key,
  reference_number text unique, -- Will be generated by trigger/function
  parent_id uuid references public.profiles(id) on delete cascade not null,
  
  -- Primary Parent Info
  parent_full_name text not null,
  parent_email text not null,
  parent_phone text not null,
  parent_phone_alt text,
  parent_address text not null,
  parent_city text not null,
  parent_region text not null,
  parent_occupation text,
  parent_employer text,
  
  -- Second Parent Info (renamed to match code expectations parent2_)
  parent2_full_name text,
  parent2_email text,
  parent2_phone text,
  parent2_relationship text,
  parent2_occupation text,
  
  -- Emergency Contacts (JSONB)
  emergency_contacts jsonb not null default '[]'::jsonb,
  
  status public.application_status default 'pending' not null,
  admin_notes text,
  reviewed_by uuid references public.profiles(id),
  reviewed_at timestamp with time zone,
  submitted_at timestamp with time zone,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Application Children Table
create table public.application_children (
  id uuid default uuid_generate_v4() primary key,
  application_id uuid references public.applications(id) on delete cascade not null,
  
  first_name text not null,
  last_name text not null,
  date_of_birth date not null,
  gender public.gender not null,
  grade_level public.grade_level not null,
  academic_year text not null,
  preferred_start_date date,
  
  -- Medical Info
  allergies text,
  medical_conditions text,
  medications text,
  special_needs text,
  dietary_restrictions text,
  blood_type text,
  doctor_name text,
  doctor_phone text,
  
  -- Education Info
  previous_school_name text,
  previous_school_address text,
  previous_school_phone text,
  previous_grade_level text,
  reason_for_leaving text,
  
  -- Documents
  birth_certificate_url text,
  previous_report_card_url text,
  immunization_record_url text,
  passport_photo_url text,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Function to generate application reference number
create or replace function public.generate_application_reference()
returns trigger
language plpgsql
as $$
declare
  year text;
  seq integer;
  new_ref text;
begin
  year := to_char(now(), 'YYYY');
  -- Get the next sequence number (you might need to create a sequence or just count)
  -- Simple loose counting for now to avoid locking issues, or use a real sequence
  select count(*) + 1 into seq from public.applications where to_char(created_at, 'YYYY') = year;
  
  new_ref := 'LGS-' || year || '-' || lpad(seq::text, 4, '0');
  NEW.reference_number := new_ref;
  return NEW;
end;
$$;

-- Trigger for reference number
create trigger set_application_reference
before insert on public.applications
for each row
when (NEW.reference_number is null)
execute function public.generate_application_reference();

-- Enable RLS
alter table public.profiles enable row level security;
alter table public.applications enable row level security;
alter table public.application_children enable row level security;

-- Policies (Basic Setup)

-- Profiles: Users can view/edit their own profile
create policy "Users can view own profile" on public.profiles
  for select using (auth.uid() = id);

create policy "Users can update own profile" on public.profiles
  for update using (auth.uid() = id);

create policy "Users can insert own profile" on public.profiles
  for insert with check (auth.uid() = id);

-- Applications: Users can view their own applications
create policy "Users can view own applications" on public.applications
  for select using (auth.uid() = parent_id);

create policy "Users can insert own applications" on public.applications
  for insert with check (auth.uid() = parent_id);

-- Application Children: Users can view/insert children for their applications
create policy "Users can view own application children" on public.application_children
  for select using (
    exists (
      select 1 from public.applications
      where applications.id = application_children.application_id
      and applications.parent_id = auth.uid()
    )
  );

create policy "Users can insert own application children" on public.application_children
  for insert with check (
    exists (
      select 1 from public.applications
      where applications.id = application_children.application_id
      and applications.parent_id = auth.uid()
    )
  );
